### PR TITLE
Add space on CHANGELOG.md for testing GitHub Actions [RHELDST-15095]

### PR DESCRIPTION
**Pull request by emanuelelevo**

### CODE REVIEW

**Comment by negillett** [comment]
Just an opinion but I think changelog updates, if not made in the associated commit, can just wait for inclusion in the next release.

**Comment by emanuelelevo** [comment]
@negillett this PR should confirm if https://github.com/release-engineering/exodus-rsync/pull/262 works as expected. Previously, any change on CHANGELOG was starting the Tag action. Now, The expectation is that such commit should not trigger the Tag action.

**Comment by negillett** [comment]
> @negillett this PR should confirm if #262 works as expected. Previously, any change on CHANGELOG was starting the Tag action. Now, The expectation is that such commit should not trigger the Tag action.

Oh, okay, I see. This PR is testing 15095.

**Review by negillett — DISMISSED** [review]

**Review by rohanpm — COMMENTED** [review]
Hmm, well I have a problem with this commit from a different angle which is that the change being made doesn't impact the users of the tool, who should be the target audience of the changelog.  I don't think the changelog should be mentioning changes internal to the project such as CI system setup.  It always bugs me when projects do this.

Put another way, if exodus-rsync 1.9.5 were released, "Updated GitHub Actions" isn't a difference which can be found if you download exodus-rsync 1.9.4 and 1.9.5 and compare them.  It's just a thing which was changed in the git repo some time between 1.9.4 and 1.9.5.  It should be irrelevant to users of the tool.

If the purpose of this commit is just to test some changed logic around the CHANGELOG.md, I'd prefer even just doing a formatting change (e.g. add one line of whitespace) with the reason for it explained in the commit message.

**Comment by emanuelelevo** [comment]
> Hmm, well I have a problem with this commit from a different angle which is that the change being made doesn't impact the users of the tool, who should be the target audience of the changelog. I don't think the changelog should be mentioning changes internal to the project such as CI system setup. It always bugs me when projects do this.
> 
> Put another way, if exodus-rsync 1.9.5 were released, "Updated GitHub Actions" isn't a difference which can be found if you download exodus-rsync 1.9.4 and 1.9.5 and compare them. It's just a thing which was changed in the git repo some time between 1.9.4 and 1.9.5. It should be irrelevant to users of the tool.
> 
> If the purpose of this commit is just to test some changed logic around the CHANGELOG.md, I'd prefer even just doing a formatting change (e.g. add one line of whitespace) with the reason for it explained in the commit message.

This has nothing to do with the app code, it's just a line for testing the Github Actions and it's supposed to be reverted. However I've just changed it to a space so we are all good.

**Review by negillett — APPROVED** [review]

**Pull request merged**
